data:
  dir: '/usr/data/cvpr_shared/proteins/enzymes_w073'
proteins:
  enzyme_trees:
    - '3.4.21'
    - '3.4.24'
  n_classes: 2
  prediction_depth: 3
training:
  network: 'basic_convnet'
  init_samples_per_class: 2000
  minibatch_size: 8
  epochs: 400
  learning_rate: 0.0001


