data:
  dir: data
proteins:
  enzyme_trees:
  - 3.4.21
  - 3.4.24
  grid_side: 64
  n_channels: 1
  n_classes: 2
  prediction_depth: 3
training:
  epochs: 1000
  init_samples_per_class: 2000
  learning_rate: 0.00002
  minibatch_size: 128
  network: l2_network
