data:
  dir: /usr/data/cvpr_shared/proteins/enzymes_w073/split_on_level4/restricted_single_64
proteins:
  enzyme_trees:
    - '3.4.21'
    - '3.4.24'
  n_classes: 2
  prediction_depth: 3
  grid_side: 64
  n_channels: 1
training:
  network: 'single_trunk_network'
  init_samples_per_class: 2000
  minibatch_size: 8
  epochs: 1000
  learning_rate: 0.0001


